### ISSUE TITLE
`library(tidymodels)` does not generate code hyperlinks in Quarto

### ISSUE THREAD

**Issue by Shitao5** [tidymodels/tidymodels#110]
I have set `code-link: true` in Quarto HTML to add hyperlinks in the code, but I noticed that only using `library(tidymodels)` does not generate the corresponding hyperlinks for the functions. The hyperlinks only appear when the package containing the respective functions is loaded, such as `library(parsnip)`.

This has caused some inconvenience. I'm not sure if this is a problem with Quarto or tidymodels. If it's an issue with my configuration, please let me know. Thank you!

![1689126156320](https://github.com/tidymodels/tidymodels/assets/68451957/d71a8055-5463-4133-8024-03a34a23dc18)

---

![1689126203265](https://github.com/tidymodels/tidymodels/assets/68451957/11bfa930-984f-453f-b248-2a3e1c97c386)

---

- tidymodels version: `1.1.0`.
- Quarto version: `1.3.433`.

**Comment by EmilHvitfeldt** [comment]
Hello @Shitao5 👋 

This is technically a {downlit} issue, I opened a issue over there. Thanks for reporting
