### ISSUE TITLE
library(tidymodels) also attaches ggplot2 -- why?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/tidymodels#112]
What is the need for `ggplot2` to be attached also? It's only for visualisation purposes. It shouldn't be part of `tidymodels`, right?

It's happening in version 1.1.0, in R 4.3.1.

**Comment by PathosEthosLogos** [comment]
I see, thanks for your answer @EmilHvitfeldt .

Then for production, I'm assuming I don't load `tidymodels` but instead use individual sub(?)-libraries instead?



Tangentially related, but I've been using `conflicted` lib for some time now, overriding any overlapping `tidyverse` functions that `tidymodels` use, with `tidytable` functions masks. It has been working without a problem, though unsure if it works as I imagine under the hood. For example, it seems that `recipes` is dependent on `dplyr` functions so `recipes` would load `dplyr`.

Do you have any suggestions on streamlining this for production without `conflicted`?

**Comment by EmilHvitfeldt** [comment]
There is also the `required_pkgs()` function that is gives you the packages needed to predictor with a given model. This is for example [used in vetiver](https://github.com/rstudio/vetiver-r/blob/09a6c5bb800549d5d0310dfa8bc16809cbb48cdc/R/tidymodels.R#L11) to determine which packages needs to be loaded in production

``` r
library(tidymodels)

wf_fit <- workflow(recipe(mpg~., data = mtcars), rand_forest(mode = "regression")) |>
  fit(data = mtcars)

wf_fit
#> ══ Workflow [trained] ══════════════════════════════════════════════════════════
#> Preprocessor: Recipe
#> Model: rand_forest()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> 0 Recipe Steps
#> 
#> ── Model ───────────────────────────────────────────────────────────────────────
#> Ranger result
#> 
#> Call:
#>  ranger::ranger(x = maybe_data_frame(x), y = y, num.threads = 1,      verbose = FALSE, seed = sample.int(10^5, 1)) 
#> 
#> Type:                             Regression 
#> Number of trees:                  500 
#> Sample size:                      32 
#> Number of independent variables:  10 
#> Mtry:                             3 
#> Target node size:                 5 
#> Variable importance mode:         none 
#> Splitrule:                        variance 
#> OOB prediction error (MSE):       5.479575 
#> R squared (OOB):                  0.8491477

required_pkgs(wf_fit)
#> [1] "recipes" "parsnip" "ranger"
```

**Comment by EmilHvitfeldt** [comment]
> Then for production, I'm assuming I don't load tidymodels but instead use individual sub(?)-libraries instead?

In production, if you want to minimize the number of packages you install, you should find the packages that you need and install those specifically, instead of doing `install.packages("tidymodels")`.
