### ISSUE TITLE
Question regarding the 

### ISSUE THREAD

**Issue by giakhang1906** [tidymodels/tidymodels#129]
Consider: 

``` r
library(tidyverse)
library(tidymodels)

nes_92 <- nes |> 
  filter(year == 1992) |> 
  select(sex, pres_vote) |> 
  drop_na() |> 
  mutate(pres_vote = case_when(
    pres_vote == "Democrat" ~ "Clinton",
    pres_vote == "Republican" ~ "Bush",
    pres_vote == "Third Party" ~ "Perot",
  ))

fit_nes <- multinom_reg() |> 
  set_engine("nnet") |> 
  set_mode("classification") |> 
  fit(pres_vote ~ sex, data = nes_92)

#> This does not work if the outcome is character variable.

```
<sub> Created on 2024-09-07 with [reprex v2.1.1](https://reprex.tidyverse.org/)

Is there anyway we can change the feature so that it also accepts outcome with character variable? Thank you.

**Comment by EmilHvitfeldt** [comment]
While it might seem temping to want character vectors to be able to be outputs. It unfortunately makes for some bad user experiences when there are problems.

With the factor right now, we know what levels the outcome can take and is able to error and warning according if something is wrong.
