### ISSUE TITLE
How to integrate tidymodels with Spark

### ISSUE THREAD

**Issue by abrahamdu** [tidymodels/tidymodels#13]
Hi,

I am wondering how to use tidymodels in Spark. My data sits in Spark environment so I am currently using Sparklyr to pull from Parquet to memory and use the modeling function provided by Sparklyr. But is there a way to replace Sparklyr with tidymodels in this setup?

**Comment by topepo** [comment]
Not really. `parsnip` has some integration with spark but the nature of spark makes it extremely difficult to integrate with other R code. We'll probably have better luck integrating h2o in the future.
