### ISSUE TITLE
Error loading tidymodels - object 'm' not found

### ISSUE THREAD

**Issue by jzadra** [tidymodels/tidymodels#26]
> require(tidymodels)
Loading required package: tidymodels
Error: package or namespace load failed for ‘tidymodels’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package rstanarm: is(module, "character"): object 'm' not found

**Comment by topepo** [comment]
The results of `sessioninfo::session_info()` would be helpful. I would also try reinstalling (along with `rstanarm`).

**Comment by juliasilge** [comment]
Let us know if you are still having trouble installing! 🙌
