### ISSUE TITLE
Pre-emptively kibosh importing/depending on tidymodels

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/tidymodels#3]
As per recent tidyverse [Do not import notice](https://www.tidyverse.org/articles/2018/06/tidyverse-not-for-packages/).

Not sure how this was accomplished on the technical end, but would probably be good to replicate here.

**Comment by juliasilge** [comment]
It's in [usethis](https://github.com/r-lib/usethis/blob/79ed2e96ea9ccb14251178f037afccd991405383/R/package.R), in `use_package()` and `refuse_package()`.

@jennybc would you accept a PR to usethis to also make tidymodels 🚨verboten🚨 ?

**Comment by jennybc** [comment]
Sure, happy to do this!

**Comment by juliasilge** [comment]
I submitted a PR for usethis. ✅ 

[Here is the email](https://github.com/tidyverse/tidyverse/blob/master/R/emails.R) that Hadley sends to folks who add tidyverse as a dependency. Do we want to add something similar here and formalize the process, as part of the revdepcheck process for tidymodels?
