### ISSUE TITLE
a call to tidy(lm) where lm is tidymodel for a lm fails

### ISSUE THREAD

**Issue by jrminter** [tidymodels/tidymodels#32]
The error reported is "no tidy method for class of model lm. The code I ran was from the sea urchins data from your examples. I ran this example on both Mac and Windows 10 on an fresh intallation of R-4.0.0. I am attaching and Rmd file. The first fail is at line 162 2nd at line 245.
[test_tidymodels.Rmd.zip](https://github.com/tidymodels/tidymodels/files/4541487/test_tidymodels.Rmd.zip)

**Comment by juliasilge** [comment]
In [parsnip 0.1.1](https://github.com/tidymodels/parsnip/blob/master/NEWS.md#parsnip-011), S3 dispatch for the `tidy()` method was fixed for R 4.0. There was a short time when it was broken for R 4.0.
