### ISSUE TITLE
tidymodels crashes RStudio

### ISSUE THREAD

**Issue by quantitative-technologies** [tidymodels/tidymodels#37]
This is a "cross-post" of the identical issue reported on `caret`:

[caret crashes RStudio](https://github.com/topepo/caret/issues/1153#issue-642433737)

**Comment by juliasilge** [comment]
This points to something unrelated to either caret or tidymodels since these two sets of packages are so unrelated. (They don't share code.)

**Comment by quantitative-technologies** [comment]
Yes, I was told the same by the `caret` maintainer. 

I have updated all my packages, and this persists. So what should I do?

**Comment by juliasilge** [comment]
I would probably start with [reinstalling a released version of RStudio](https://rstudio.com/products/rstudio/download/#download).

**Comment by quantitative-technologies** [comment]
I reproduced this on both the most recent stable and daily build RStudio versions.

**Comment by juliasilge** [comment]
You could either go with a direction pretty certain to solve your problem (reinstall R altogether and all packages) or perhaps try loading the individual packages in tidymodels ([check out the README](https://github.com/tidymodels/tidymodels)) to see which one is causing the crash. The fact that both caret and tidymodels are causing crashes lead me to suspect that something is seriously borked with R itself so I would go with the first option TBH.

**Comment by quantitative-technologies** [comment]
I purged R: `sudo apt purge r-base-core` and reinstalled everything, moving up to R version 4.0.1.

So I agree there is a serious problem with R, but I don't believe it's specific to my installation. This time RStudio dumped some error messages when it crashed as shown [here](https://ibb.co/nwxSqHH).

**Comment by juliasilge** [comment]
I don't believe this is related to code within tidymodels. I recommend considering this a crash of RStudio and [following the instructions in this post to report the details](https://support.rstudio.com/hc/en-us/articles/200488518-RStudio-Crashed) and find the source of the problem.

I wish you the best of luck! 💪
