### ISSUE TITLE
Pkgdown site

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/tidymodels#4]
We should build a centralized site like tidyverse.org. I think the headline announcement needs to be:

- the API is under development and we are going to get things wrong for a while, so don't build on top of this stuff for a while and expect abstractions to change

i.e. we don't want people to bake early mistakes / experiments into their code and then get stuck with them.

**Comment by juliasilge** [comment]
We have now published [tidymodels.org](https://www.tidymodels.org/)! 🎉
