### ISSUE TITLE
Re-licensing tidymodels metapackage ✨

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/tidymodels#51]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/tidymodels/graphs/contributors). 

@alexpghayes, @skadauke, would you permit us to re-license tidymodels with the MIT license? If so, please comment "I agree" below.

* [x] [@alexpghayes](https://github.com/tidymodels/tidymodels/commits?author=alexpghayes)  
* [x] [@skadauke](https://github.com/tidymodels/tidymodels/commits?author=skadauke)

**Comment by alexpghayes** [comment]
I agree

**Comment by skadauke** [comment]
I didn’t think I would have a say in this but don’t let me stand in the way!

Sent from my iPhone, please forgive brevity and typos.
________________________________

**Comment by juliasilge** [comment]
HAHA @skadauke can you comment "I agree"? 😆

**Comment by skadauke** [comment]
I agree

Sent from my iPhone, please forgive brevity and typos.
________________________________
