### ISSUE TITLE
Latest updates with R + R Studio, predicting a Parsnip object no longer works?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/tidymodels#62]
(I couldn't get `reprex` to work, sorry)

## The problem

It's a simple glmnet model, and predict() results in 'Error in lambda[1] - s : non-numeric argument to binary operator'. I've been trying to use predict() with various forms of dataframe formats, but they don't seem to work. I've tried 1) excluding the dependent variable, 2) including the dependent variable with sliced data, 3) including dependent variable with NA values in it, and others.

The last three lines of code in the reproducible example each throw Error in lambda[1] - s : non-numeric argument to binary operator debug messages. I made sure that all of the variables are numeric in both df and df_slice but still unsure of what is going on. I just want to get the predicted/fitted values, as well as 'future' values if I were to do a train-test split. Why is this not working?

## Reproducible example

```
library(tidyverse)
library(lubridate)
library(tidymodels)

df <- data.frame(y  = sample(5000000:120000000, 100, replace = TRUE),
                 yearr = sample(2015:2021, 100, replace = TRUE),
                 monthh = sample(1:12, 100, replace = TRUE),
                 dayy = sample(1:31, 100, replace = TRUE))

rm(df_slice)
df_slice = df |>
  slice(1:50) |>
  select(yearr, monthh, dayy) |>
  mutate(y = NA)

m = linear_reg(mode = 'regression', penalty = varying(), mixture = 0.6) |>
  set_engine("glmnet") |>
  fit(y ~ ., data = df)

predict(m, df_slice)

predict.model_fit(m, df_slice)

predict_raw(m, df_slice)
```

I used similar code previously, so this should work. The only difference is that I now use the latest version of R, R Studio, and native pipes.

**Comment by topepo** [comment]
You reprex is fine 😺 

The main issue is `penalty = varying()`. I don't think that this worked in previous versions of `parsnip` either (but I have not verified that). 

Keep in mind that the last release of `parsnip` has in the [news file](https://parsnip.tidymodels.org/news/index.html#model-specification-changes):

* For models with `glmnet` engines: 

  - A single value is required for `penalty` (either a single numeric value or a value of `tune()`) (#481).
  - A special argument called `path_values` can be used to set the `lambda` path as a specific set of numbers (independent of the value of `penalty`). A pure ridge regression models (i.e., `mixture = 1`) will generate incorrect values if the path does not include zero. See issue #431 for discussion (#486).

It does work if you give it a number: 

``` r
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip

df <- data.frame(y  = sample(5000000:120000000, 100, replace = TRUE),
                 yearr = sample(2015:2021, 100, replace = TRUE),
                 monthh = sample(1:12, 100, replace = TRUE),
                 dayy = sample(1:31, 100, replace = TRUE))

rm(df_slice)
#> Warning in rm(df_slice): object 'df_slice' not found
df_slice = df |>
  slice(1:5) |>
  select(yearr, monthh, dayy) |>
  mutate(y = NA)

m = linear_reg(mode = 'regression', penalty = 1, mixture = 0.6) |>
  set_engine("glmnet") |>
  fit(y ~ ., data = df)

predict(m, df_slice)
#> # A tibble: 5 x 1
#>       .pred
#>       <dbl>
#> 1 60698538.
#> 2 71753019.
#> 3 66008735.
#> 4 76521869.
#> 5 63140146.

predict.model_fit(m, df_slice)
#> # A tibble: 5 x 1
#>       .pred
#>       <dbl>
#> 1 60698538.
#> 2 71753019.
#> 3 66008735.
#> 4 76521869.
#> 5 63140146.

predict_raw(m, df_slice)
#>          1
#> 1 60698538
#> 2 71753019
#> 3 66008735
#> 4 76521869
#> 5 63140146
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by PathosEthosLogos** [comment]
Ok nice, thanks! How is the debug message connected to this problem?

**Comment by topepo** [comment]
I'm not sure what you mean.
