### ISSUE TITLE
[New Feature]: To include some kind of model interpretability in workflow.

### ISSUE THREAD

**Issue by coforfe** [tidymodels/tidymodels#63]
Hi `tidymodels'` Team!

The concept of model interpretability/explainability is, more and more, a required step when presenting model's results to stakeholders in any analytical enterprise project.

I see that [H2O has already](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/explain.html) integrated this concept within their solution opensource (also in their enterpreise) solution. And it runs relatively fast for the kind of calculations involved in these kind of interpretability issues (SHAP values in particular).

With [DALEX](https://htmlpreview.github.io/?https://github.com/ModelOriented/DALEX-docs/blob/master/vignettes/DALEX_parsnip.html), it is quite straightforward to get model's interpretability for any kind of model no matter the wrapper used (caret, h2o, parsnip or mlr). Besides DALEX it is possible to use another third party package (vip, pdp, etc).

To me having a more clean and direct way of integrating model's interpretability within tidymodels' workflow would be a big plus.

Which are your thoughts about this?.

Thanks!
Carlos Ortega

**Comment by topepo** [comment]
As you mention, there are several packages that support these computations using the objects produced by our packages. We are unlikely to make new software for tasks where there are already several good options. '

Can you be more specific about what is missing? 

Is it more documentation that you are interested in? If so, there is a [draft book chapter](https://github.com/tidymodels/TMwR/pull/151) that should be merged into [tmwr.org](https://www.tmwr.org/) soon.

**Comment by coforfe** [comment]
Thanks!.

Yes, the documentation will help a lot. Thanks for sharing this new interpretability chapter.

What I think it would help is to have something equivalent to `add_model()` or `add_recipe()` but for interpretability to be included in a `workflow()` like an **`add_explain()`**, that would encapsulate DALEX's functions for instance.

Thanks again,
Carlos.

**Comment by juliasilge** [comment]
You can check out our [now-published chapter on explainability options here](https://www.tmwr.org/explain.html).
