### ISSUE TITLE
add_model() ==> add_engine() ?

### ISSUE THREAD

**Issue by scottlyden** [tidymodels/tidymodels#81]
This is a trivial semantic thing, but it makes me a little nutty every time I type something like workflow %>% add_model() to add an object that (to me, at least) is nothing more than the engine for a model.  Tidymodels' error messages even seem to acknowledge as much...

workflow() %>% translate()
Error: Please set an engine.

I'm sorry to take up your attention with an issue that may say more about my fragile mental state than your excellent framework, and I appreciate all your brilliant work to make R even more awesome, but what would you think about (at least) adding a synonym add_engine() function so that I can relax my OCD impulse to make that the first step of any tidymodels workflow for me?  :-)

**Comment by EmilHvitfeldt** [comment]
We are currently happy with the way {parsnip} and {workflows} work together at the moment. {parsnip} created **model specifications** using function such as `linear_reg()` and `nearest_neighbor()`. These model specifications support a number of different engine to do the calculation.
{workflows} allows you to combine a model specification with a data preprocessor.

I agree that the error message from `translate()` is misleading. [`translate()`](https://parsnip.tidymodels.org/reference/translate.html) is only intended to be used on model specifications, not workflows. We could do better to update that particular error.

``` r
library(tidymodels)

base_wf <- workflow() %>%
  add_formula(mpg ~ .)
  
lm_spec <- linear_reg() %>%
  set_engine("lm")

lm_spec %>%
  translate()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm 
#> 
#> Model fit template:
#> stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())

base_wf %>%
  translate()
#> Error in `translate()`:
#> ! Please set an engine.
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by scottlyden** [comment]
Thanks for your response, Emil.
To me, of course, it's the error message that is right and the function name that is 'wrong.'
Even Max and Julia's book says things like: "Workflows have a fit() method that can be used to create the model," implicitly acknowledging that a "model" hasn't been created until it is fit.  Until then, I believe, you just have an engine.
Best,
Scott

    On Sunday, March 6, 2022, 11:57:35 AM PST, Emil Hvitfeldt ***@***.***> wrote:  
 
 


We are currently happy with the way {parsnip} and {workflows} work together at the moment. {parsnip} created model specifications using function such as linear_reg() and nearest_neighbor(). These model specifications support a number of different engine to do the calculation.
{workflows} allows you to combine a model specification with a data preprocessor.

I agree that the error message from translate() is misleading. translate() is only intended to be used on model specifications, not workflows. We could do better to update that particular error.
library(tidymodels)

base_wf <- workflow() %>%
  add_formula(mpg ~ .)
  
lm_spec <- linear_reg() %>%
  set_engine("lm")

lm_spec %>%
  translate()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm 
#> 
#> Model fit template:
#> stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())

base_wf %>%
  translate()
#> Error in `translate()`:
#> ! Please set an engine.
Created on 2022-03-06 by the reprex package (v2.0.1)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EmilHvitfeldt** [comment]
A workflow is a container that can combine a model specification and a preprocessing specification. The model specification itself has an engine that delegates what software should be used to fit that model. This is part of the convention illustrated in [Figure 7.2](https://www.tmwr.org/workflows.html#fig:good-workflow), where we think of preprocessing and model fitting together as part of the model workflow.

Saying that an unfit workflow is an engine would be wrong since the engine only describes part of half of what goes into creating a workflow.

**Comment by juliasilge** [comment]
I totally feel your pain @scottlyden; it is basically hilarious to me when I realize how overloaded the term "model" is in these domains. It can mean so many things! However, we have formulated a pretty specific set of terms to discuss what makes a model in tidymodels (see the discussion [here](https://parsnip.tidymodels.org/articles/parsnip.html) and [here](https://www.tmwr.org/models.html#create-a-model), and in that context, it really is a parsnip model specification you are adding with `add_model()` (not only the engine).

We definitely acknowledge that this is not a perfect framing for what is a complex topic, but we think it is the best fit for how our software is designed. Thanks for the discussion! 🙌

**Comment by scottlyden** [comment]
Thanks for the response, Julia, and thanks for your huge contributions to R.


    On Thursday, March 10, 2022, 01:49:16 PM PST, Julia Silge ***@***.***> wrote:  
 
 


I totally feel your pain @scottlyden; it is basically hilarious to me when I realize how overloaded the term "model" is in these domains. It can mean so many things! However, we have formulated a pretty specific set of terms to discuss what makes a model in tidymodels (see the discussion here and here, and in that context, it really is a parsnip model specification you are adding with add_model() (not only the engine).

We definitely acknowledge that this is not a perfect framing for what is a complex topic, but we think it is the best fit for how our software is designed. Thanks for the discussion! 🙌
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
