### ISSUE TITLE
potential library problem

### ISSUE THREAD

**Issue by EngrStudent** [tidymodels/tidymodels#87]
I'm not sure if this is a pacman issue or not, but I pull in my libraries using the pacman "p_load".

When I installed the required libraries shown on the intro page, I got an error saying I also needed to install "rstanarm".  It was trivial to fix, but might be dependency drift.  Might want to do a quick check there.

Because my system is Ubuntu, the package install had a LOT of text on the console as part of the installation process and washed away the exact text and feedback.

**Comment by EmilHvitfeldt** [comment]
Hello @EngrStudent! Can you talk us through the events in a little more detail. Am I understanding you correctly that you called `p_load("tidymodels")` and received an error?

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
