### ISSUE TITLE
including `broom.mixed` in future versions?

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/tidymodels#9]
In addition to `broom`, are there plans to also incorporate `broom.mixed` - its "mixed-effects" cousin - in the `tidymodels` universe? After all, `broom.mixed` is nothing but a more specialized component of the `broom` package.

**Comment by IndrajeetPatil** [comment]
@bbolker and @alexpghayes What do you think?

**Comment by alexpghayes** [comment]
I think this is a reasonable idea, but I don't think `broom.mixed` follows all the same conventions as `broom` at the moment, and adding `broom.mixed` to the `tidymodels` before sorting these discrepancies out could result in confusion.

**Comment by bbolker** [comment]
I don't have strong feelings. I guess I would be curious what the conventions are/what the discrepancies are/how to go about finding them (I know thanks to @IndrajeetPatil that there are a couple of non-tibbles returned -- that'll be easy to fix -- but I'm not aware of other departures)

**Comment by topepo** [comment]
We can also add it via the [tagging system](https://github.com/tidymodels/tidymodels/blob/master/R/tags.R).

**Comment by topepo** [comment]
If you'd like to do a PR to add it as a tag, please do.
