### ISSUE TITLE
A Thank You

### ISSUE THREAD

**Issue by mlane3** [tidymodels/tidymodels#99]
@DavisVaughan @topepo @juliasilge and [christophM](https://github.com/christophM/iml/)
So after... many conversations my team's model is finally going to be made public either this year or next. 
[https://www.linkedin.com/pulse/justice-timely-predicting-duration-felony-case-justyna/?trackingId=w5B2Uo2fTs6gPphK3DU43g%3D%3D](https://www.linkedin.com/pulse/justice-timely-predicting-duration-felony-case-justyna/?trackingId=w5B2Uo2fTs6gPphK3DU43g%3D%3D)

There was one part that was a bit tricky about getting IML's lime (because there was not a better one at the time) talking with tidymodel's xgboost.  I had to make m own custom functions.  And then I had to write my own dplyr() group by statement to supplement bupar(*)
So as thanks I would like to share that part of the LIME code for tidymodels in case anyone comes across a similar situation.
https://gist.github.com/mlane3/99a51a6cab4eeff16fab6525790cdbe2

If anything it might make a good example for the next edition of your tidymodels book.  I am pretty sure it's the most customized you can ever make a metric/predictor function. 

(*)P.S. Basically a purr-like group by for loop is what I needed.   Not sure how useful that part of the code would be as the dplyr devs mentioned that the case was too specific when I asked in dplyr.  It was required though for the recipe function to work properly.   
P.P.S.  Also I could never get this to work with models that run in parallel or distributed.  This is primarily due to the fact that the tidy model models delete their ports at the time and then tidy models tries to reuse them when it calls to IML.

**Comment by EmilHvitfeldt** [comment]
Thank you so much for this feedback @mlane3 🙌

This information is very useful for us going forward. And we have it saved for when we get around to working with IML/LIME.

Thank you again for this information!
